apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: pg
  labels:
    app: pg
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pg
  template:
    metadata:
      labels:
        name: pg
    spec:
      containers:
      - image: postgres:14
        name: message-db
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: pg-pv-storage
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: pg-secret
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-secret
              key: password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - exec pg_isready -U "qlik" -h 127.0.0.1 -p 5432
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - exec pg_isready -U "qlik" -h 127.0.0.1 -p 5432
          initialDelaySeconds: 30
          timeoutSeconds: 5
      volumes:
      - name: pg-pv-storage
        persistentVolumeClaim:
          claimName: pg-pv-claim
      
      
        