apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: pg-pv-claim
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi