apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    name: redis-svc
  name: redis-svc
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    name: redis
